services:
  # See https://render.com/docs/blueprint-spec for more info on render blueprints
  - type: web
    name: telemetry-uindy-camp
    env: python
    plan: free
    # A requirements.txt file must exist
    buildCommand: pip install -r requirements.txt
    # A src/app.py file must exist and contain `server=app.server`
    startCommand: gunicorn --chdir src app:server --timeout 120 --keep-alive 5 --max-requests 1000 --max-requests-jitter 100
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
